# Generated by Django 5.1.2 on 2024-10-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название изображения')),
                ('file_path', models.CharField(max_length=255, verbose_name='Путь к файлу')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('resolution', models.CharField(max_length=20, verbose_name='Разрешение изображения')),
                ('size', models.PositiveIntegerField(verbose_name='Размер изображения в байтах')),
            ],
        ),
    ]
